#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_ENV="${ROOT_DIR}/.env"
if [[ ! -f "${BASE_ENV}" ]]; then
  BASE_ENV="${ROOT_DIR}/.env.example"
fi
RUNTIME_ENV="${ROOT_DIR}/.env.listen-demo"

USED_PORTS=""
RESERVED_PORT=""

is_port_busy() {
  local port="$1"
  lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1
}

reserve_port() {
  local port="$1"
  while true; do
    if [[ " ${USED_PORTS} " == *" ${port} "* ]] || is_port_busy "${port}"; then
      port=$((port + 1))
      continue
    fi
    USED_PORTS="${USED_PORTS} ${port}"
    RESERVED_PORT="${port}"
    return 0
  done
}

reserve_port "${POSTGRES_PORT:-5432}"; POSTGRES_PORT="${RESERVED_PORT}"
reserve_port "${CLICKHOUSE_HTTP_PORT:-8123}"; CLICKHOUSE_HTTP_PORT="${RESERVED_PORT}"
reserve_port "${CLICKHOUSE_NATIVE_PORT:-9009}"; CLICKHOUSE_NATIVE_PORT="${RESERVED_PORT}"
reserve_port "${MINIO_PORT:-9000}"; MINIO_PORT="${RESERVED_PORT}"
reserve_port "${MINIO_CONSOLE_PORT:-9001}"; MINIO_CONSOLE_PORT="${RESERVED_PORT}"
reserve_port "${BACKEND_API_PORT:-8000}"; BACKEND_API_PORT="${RESERVED_PORT}"
reserve_port "${FRONTEND_PORT:-3000}"; FRONTEND_PORT="${RESERVED_PORT}"
reserve_port "${N8N_PORT:-5678}"; N8N_PORT="${RESERVED_PORT}"
reserve_port "${PROMETHEUS_PORT:-9090}"; PROMETHEUS_PORT="${RESERVED_PORT}"
reserve_port "${GRAFANA_PORT:-3001}"; GRAFANA_PORT="${RESERVED_PORT}"
reserve_port "${JAEGER_UI_PORT:-16686}"; JAEGER_UI_PORT="${RESERVED_PORT}"
reserve_port "${OTEL_GRPC_PORT:-4317}"; OTEL_GRPC_PORT="${RESERVED_PORT}"
reserve_port "${OTEL_HTTP_PORT:-4318}"; OTEL_HTTP_PORT="${RESERVED_PORT}"
reserve_port "${OTEL_METRICS_PORT:-8889}"; OTEL_METRICS_PORT="${RESERVED_PORT}"

cat > "${RUNTIME_ENV}" <<EOF
# Auto-generated by scripts/listen-demo.sh
POSTGRES_PORT=${POSTGRES_PORT}
CLICKHOUSE_HTTP_PORT=${CLICKHOUSE_HTTP_PORT}
CLICKHOUSE_NATIVE_PORT=${CLICKHOUSE_NATIVE_PORT}
MINIO_PORT=${MINIO_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
BACKEND_API_PORT=${BACKEND_API_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
N8N_PORT=${N8N_PORT}
PROMETHEUS_PORT=${PROMETHEUS_PORT}
GRAFANA_PORT=${GRAFANA_PORT}
JAEGER_UI_PORT=${JAEGER_UI_PORT}
OTEL_GRPC_PORT=${OTEL_GRPC_PORT}
OTEL_HTTP_PORT=${OTEL_HTTP_PORT}
OTEL_METRICS_PORT=${OTEL_METRICS_PORT}
PUBLIC_API_URL=http://localhost:${BACKEND_API_PORT}
PUBLIC_MINIO_URL=http://localhost:${MINIO_PORT}
NEXT_PUBLIC_API_BASE_URL=/api
EOF

docker compose --env-file "${BASE_ENV}" --env-file "${RUNTIME_ENV}" up --build -d

API_URL="http://localhost:${BACKEND_API_PORT}"
for _ in $(seq 1 90); do
  if curl -fsS "${API_URL}/health" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

curl -fsS -X POST "${API_URL}/admin/seed-demo" >/dev/null 2>&1 || true

echo "SonataOps Studio listen-demo is ready."
echo "Frontend:  http://localhost:${FRONTEND_PORT}"
echo "Backend:   http://localhost:${BACKEND_API_PORT}/docs"
echo "Listen UI: http://localhost:${FRONTEND_PORT}/listen"
echo "MinIO:     http://localhost:${MINIO_CONSOLE_PORT}"
echo "Grafana:   http://localhost:${GRAFANA_PORT}"
echo "Jaeger:    http://localhost:${JAEGER_UI_PORT}"
echo "n8n:       http://localhost:${N8N_PORT}"
echo "Runtime env file: ${RUNTIME_ENV}"
echo "Stop: docker compose --env-file \"${BASE_ENV}\" --env-file \"${RUNTIME_ENV}\" down"
