PRESETS: dict[str, dict[str, float]] = {
    "Executive Minimal": {
        "base_freq": 220.0,
        "pitch_span": 42.0,
        "transient_gain": 0.06,
        "brightness_bias": 0.34,
        "width_bias": 0.28,
        "third_ratio": 1.2599,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.42,
        "default_glitch": 0.08,
        "default_harmonizer": 0.30,
        "default_pad_depth": 0.58,
        "default_ambient_mix": 0.36,
        "tempo_bias": -4.0,
    },
    "Risk Tension": {
        "base_freq": 174.0,
        "pitch_span": 60.0,
        "transient_gain": 0.20,
        "brightness_bias": 0.58,
        "width_bias": 0.33,
        "third_ratio": 1.1892,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.66,
        "default_glitch": 0.42,
        "default_harmonizer": 0.48,
        "default_pad_depth": 0.52,
        "default_ambient_mix": 0.40,
        "tempo_bias": 6.0,
    },
    "Growth Momentum": {
        "base_freq": 247.0,
        "pitch_span": 68.0,
        "transient_gain": 0.14,
        "brightness_bias": 0.50,
        "width_bias": 0.44,
        "third_ratio": 1.2599,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.56,
        "default_glitch": 0.18,
        "default_harmonizer": 0.52,
        "default_pad_depth": 0.62,
        "default_ambient_mix": 0.46,
        "tempo_bias": 8.0,
    },
    "State Azure": {
        "base_freq": 207.65,
        "pitch_span": 36.0,
        "transient_gain": 0.10,
        "brightness_bias": 0.43,
        "width_bias": 0.62,
        "third_ratio": 1.3348,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.54,
        "default_glitch": 0.22,
        "default_harmonizer": 0.66,
        "default_pad_depth": 0.90,
        "default_ambient_mix": 0.86,
        "tempo_bias": -6.0,
    },
    "Glitch Harmonics": {
        "base_freq": 196.0,
        "pitch_span": 74.0,
        "transient_gain": 0.30,
        "brightness_bias": 0.70,
        "width_bias": 0.52,
        "third_ratio": 1.1892,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.82,
        "default_glitch": 0.76,
        "default_harmonizer": 0.74,
        "default_pad_depth": 0.46,
        "default_ambient_mix": 0.40,
        "tempo_bias": 14.0,
    },
    "Ambient Boardroom": {
        "base_freq": 233.08,
        "pitch_span": 28.0,
        "transient_gain": 0.05,
        "brightness_bias": 0.30,
        "width_bias": 0.56,
        "third_ratio": 1.2599,
        "fifth_ratio": 1.4983,
        "default_intensity": 0.36,
        "default_glitch": 0.05,
        "default_harmonizer": 0.56,
        "default_pad_depth": 0.94,
        "default_ambient_mix": 0.80,
        "tempo_bias": -10.0,
    },
}


def resolve_preset(name: str) -> dict[str, float]:
    return PRESETS.get(name, PRESETS["Executive Minimal"])
